name: Test Sample.py

on:
  pull_request:
    branches:
      - wk7-rebase
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Run test
        run: |
          OUTPUT=$(python sample.py)
          if [ "$OUTPUT" != "20" ]; then
            echo "Test failed! Expected output: 20, but got: $OUTPUT"
            exit 1
          fi

